version: '3'

networks: 
    dev:

services: 
    nginx:
        build: nginx
        container_name: nginx_server
        ports: 
            - 8000:80
        links: 
            - php
        volumes: 
            - ./src:/var/www/chityeaung
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        networks: 
            - dev

    php:
        build: php
        container_name: php_fpm
        volumes: 
            - ./src:/var/www/chityeaung
        networks: 
            - dev

    db:
        image: mysql
        container_name: mysql_db
        environment: 
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_USER: chitgyi
            MYSQL_PASSWORD: secret
            MYSQL_DATABASE: test_db
        networks: 
            - dev
    
    

        
