@url = http://[::1]:8080/api/v1

###

POST  {{url}}/register
content-type: application/json

{
    "name": "Aung Aung",
    "email": "halo@student.com",
    "password": "password"
}

### 

POST {{url}}/login
Content-Type: : application/json

{
    "email": "halo@student.com",
    "password": "password"
}

###

GET  {{url}}/profile
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9bOjoxXTo4MDgwXC9hcGlcL3YxXC9yZWdpc3RlciIsImlhdCI6MTYwNDQ2ODY5NiwiZXhwIjoxNjA0NDcyMjk2LCJuYmYiOjE2MDQ0Njg2OTYsImp0aSI6IlM0YVR3SUlMZTNzeWRYZnQiLCJzdWIiOjEsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.8zzdKU7Pa479nGKMWMKJsczx8Mskeq0OiKoqprdcXKg

###
POST  {{url}}/address
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9bOjoxXTo4MDgwXC9hcGlcL3YxXC9yZWdpc3RlciIsImlhdCI6MTYwNDQ2ODY5NiwiZXhwIjoxNjA0NDcyMjk2LCJuYmYiOjE2MDQ0Njg2OTYsImp0aSI6IlM0YVR3SUlMZTNzeWRYZnQiLCJzdWIiOjEsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.8zzdKU7Pa479nGKMWMKJsczx8Mskeq0OiKoqprdcXKg

{
    "country": "Myanmar",
    "city": "Meiktila",
    "address": "Address"
}

###

POST  {{url}}/article
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9bOjoxXTo4MDgwXC9hcGlcL3YxXC9yZWdpc3RlciIsImlhdCI6MTYwNDQ2ODY5NiwiZXhwIjoxNjA0NDcyMjk2LCJuYmYiOjE2MDQ0Njg2OTYsImp0aSI6IlM0YVR3SUlMZTNzeWRYZnQiLCJzdWIiOjEsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.8zzdKU7Pa479nGKMWMKJsczx8Mskeq0OiKoqprdcXKg

{
    "title": "Velit eu deserunt eiusmod do elit ipsum sunt nulla.",
    "body": "Magna pariatur amet quis proident sint. Id incididunt enim cillum tempor ad sunt esse consequat consectetur nulla culpa aute. Consequat consectetur non ea dolor eiusmod non ipsum dolore non irure. Sit commodo culpa labore aliqua non reprehenderit. Aliqua ipsum dolore commodo in qui."
}


###

GET  {{url}}/articles?page=2
Content-Type: application/json


###

GET  {{url}}/myarticles?page=2
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9sb2NhbGhvc3Q6ODAwMFwvYXBpXC92MVwvbG9naW4iLCJpYXQiOjE2MDQ0MDIwNzgsImV4cCI6MTYwNDQwNTY3OCwibmJmIjoxNjA0NDAyMDc4LCJqdGkiOiI2RkRFMGc2RllCMWc3V1hTIiwic3ViIjoxLCJwcnYiOiIyM2JkNWM4OTQ5ZjYwMGFkYjM5ZTcwMWM0MDA4NzJkYjdhNTk3NmY3In0.c1Iz1BY78AjlZzpvoNjx-lypRcS03h1TtdNZlLC4lKs
